# Generated by Django 5.1.6 on 2025-02-10 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingway', '0002_ride_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='ride',
            name='ending_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='ending_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='ending_location_type',
            field=models.CharField(choices=[('SEARCH', 'Search All'), ('ADDRESS', 'Address'), ('AIRPORT', 'Airport'), ('LANDMARK', 'Landmark')], default='SEARCH', max_length=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='num_bags',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='num_kids',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='num_travelers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ride',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('TRANSFER', 'Transfer'), ('HOURLY', 'Hourly')], default='TRANSFER', max_length=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='starting_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='starting_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='starting_location_type',
            field=models.CharField(choices=[('SEARCH', 'Search All'), ('ADDRESS', 'Address'), ('AIRPORT', 'Airport'), ('LANDMARK', 'Landmark')], default='SEARCH', max_length=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('location_type', models.CharField(choices=[('SEARCH', 'Search All'), ('ADDRESS', 'Address'), ('AIRPORT', 'Airport'), ('LANDMARK', 'Landmark')], default='SEARCH', max_length=10)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='findingway.ride')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('ride', 'order')},
            },
        ),
    ]
