# Generated by Django 5.1.6 on 2025-02-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingway', '0003_alter_ride_options_ride_ending_lat_ride_ending_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ending_flight_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='starting_flight_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stop',
            name='flight_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
